поправка грамматической ошибки
TemirkhanN/test-blog pull request #6
Opened 2017-06-22 22:39 UTC by SerRashin

2017-06-22 22:59 UTC, TemirkhanN requested changes

2017-06-22 22:59 UTC, TemirkhanN commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +
Лишний отступ

2017-06-22 22:59 UTC, TemirkhanN commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +     * Проверка фильтрации при отсутствии автора
Посмотри на противоположный тест чуть ниже и реши, какой комментарий выберешь. А то внизу у тебя фильтр, а тут фильтрация

2017-06-22 22:59 UTC, TemirkhanN commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +     * Проверка установки автора
Проверка установки фильтра по автору

2017-06-22 22:59 UTC, TemirkhanN commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +        $post->setAuthor($author);
Перед этим проверь, что дефолтное значение автора то, чем должно являться. Это можно сделать прямо перед установкой setAuthor

2017-06-22 22:59 UTC, TemirkhanN commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +        $post = new PostFilter([]);
То же самое, что и с автором. Убедись, что по-умолчанию у тебя публикации фильтруются по конкретному значению.

2017-06-22 23:33 UTC, SerRashin commented on test/Temirkhan/Blog/Filter/PostFilterTest.php
> +        $post->setAuthor($author);
надеюсь я тебя правильно понял
$this->assertEquals(null, $post->getAuthor());

2017-06-23 08:31 UTC, TemirkhanN approved these changes

2017-06-23 08:32 UTC, merged