указал возвращаемые типы для тестов
TemirkhanN/test-blog pull request #8
Opened 2017-06-25 16:47 UTC by SerRashin

2017-06-25 17:40 UTC, SerRashin commented
@TemirkhanN посмотрел покрытие, понял что плохо покрыл) сейчас покрою остальное

2017-06-25 18:12 UTC, SerRashin commented
@TemirkhanN Тим, посмотри тесты ролей, насколько корректно я сделал ?

2017-06-25 19:17 UTC, TemirkhanN requested changes

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $date = new DateTime('2017-06-25 12:38:27');
Некорректно

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +            (new DateTime())->format('Y-m-d'),
Еще более некорректно. Этот тест вводит в заблуждение, а иногда по теории вероятности, может даже отваливаться

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $user = new User();
User фигурирует в каждом из тесткейсов. Убери дублирование - вынеси в setUp/tearDown

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertNull($user->addRole($role));
То есть как это? Ты проверяешь реализацию что ли? Думай о задаче проще - у тебя уже есть роль в списке. Ты просто не хочешь, чтобы одна и та же роль добавлялась два раза.

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertEquals([ $role ], $user->getRoles());
assertContains

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertEquals([ $role ], $user->getRoles());
Тебя интересует не то, что в конечном итоге там будет именно такой массив, а то, что роль $role была в него добавлена. Так-то там может по-умолчанию быть роль какая-нибудь и это не должно рушить тесты в этом месте

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertNull($user->removeRole($role));
То же самое, что и выше

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertEquals([], $user->getRoles());
Возвращается всегда массив. assertEmpty более говорящий тест

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertNull($user->eraseCredentials());
Тест, который ничего не делает - даже интерфейс говорит, что этот метод - процедура. Тебе нужно убедиться, что этот метод ничего не сделает с User'ом.

2017-06-25 19:17 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $date = new DateTime('2017-06-25 12:38:27');
Считаю, что этот тест - знак того, что нужно изменить реализацию. В частности, передавать дату регистрации в конструктор. Тем более, что за инициализацию нового пользователя отвечает сервис регистрации и дату регистрации должен назначать он. Напиши тест, как ты это видишь и, соответственно, функционал реализуй на стороне UserService

2017-06-25 23:07 UTC, SerRashin commented
@TemirkhanN посмотри последние тесты, я чет в тупике по поводу проверки removeRole - return;
и глянь насчет - eraseCredentials

и вобщ в целом какие будут замечания ? именование, комментарии и т.д. ?

2017-06-25 23:28 UTC, TemirkhanN commented on src/Temirkhan/UserBundle/Entity/User.php
> +    public function __construct(DateTime $regDate = null)
И где у нас по доменной модели дата регистрации пользователя может быть null?)

2017-06-25 23:28 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +     * Сущьность пользователя
Сущность. Но, пожалуй, можно слово "сущность" в системе не использовать. Если ты скажешь "Пользователь", мы уже будем понимать, о чем речь

2017-06-25 23:28 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->user->setLogin($login);
А тут точно все ок? Почему тест про userName, а работаем с логином?

2017-06-25 23:28 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertCount(count($this->user->getRoles()), array_unique($this->user->getRoles()));
Направление взял верное, но что-то сложновато. У меня ушло секунд 8, чтобы понять, что происходит. Это проверка на то, что в ролях только уникальные значения. Чтобы повысить читаемость, вынеси значения в переменные и потом сравнивай. 

И ты забыл проверить, что по-умолчанию у пользователя нет ролей.

2017-06-25 23:28 UTC, TemirkhanN commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertEquals(new User(), $this->user);
Наверно, будет лучше склонировать $this->user в переменную, а потом вызвать eraseCredentials и проверить, что склонированный и оригинальный объекты не отличаются по значениям. Это на обсуждение, а не на поправить. Прикинь что да как, потом поделишься соображениями

2017-06-26 06:48 UTC, SerRashin commented on src/Temirkhan/UserBundle/Entity/User.php
> +    public function __construct(DateTime $regDate = null)
@TemirkhanN а что если мы напишем метод обновления данных профиля ? в таком случае нам никак уж не понадобится regDate или я не прав ?

2017-06-26 06:48 UTC, SerRashin commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +     * Сущьность пользователя
@TemirkhanN вас понял

2017-06-26 06:49 UTC, SerRashin commented on test/Temirkhan/UserBundle/Entity/UserTest.php
> +        $this->assertCount(count($this->user->getRoles()), array_unique($this->user->getRoles()));
@TemirkhanN вас понял

2017-06-26 08:50 UTC, TemirkhanN commented on src/Temirkhan/UserBundle/Entity/User.php
> +    public function __construct(DateTime $regDate = null)
@SerRashin что ты имеешь ввиду? В смысле, как это все связано?

2017-07-12 12:29 UTC, SerRashin commented
Тим, я тут внес коррективы в domain.txt привел к формату md
и хочу расписать все по DDD как можно лучше :)

2017-07-12 13:06 UTC, TemirkhanN commented
Если бы запулил последние правки отдельной веткой, можно было бы сразу в мастер влить)

2017-09-27 08:41 UTC, SerRashin commented on src/Temirkhan/UserBundle/Entity/User.php
> +    public function __construct(DateTime $regDate = null)
@TemirkhanN да простит меня аллах, что за хуйню я нес...

2017-10-17 08:42 UTC, closed without merging